import streamlit as st
import logging

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger('insights_display')

def display_insights(insights, property_name=""):
    """
    Display GPT-generated insights in the Streamlit UI with consistent styling
    """
    logger.info(f"Displaying detailed insights for property: {property_name}")

    # Create a container with a distinctive background
    with st.container():
        # Display the executive summary
        st.markdown("""
            <div class="reborn-section-title executive-summary">Executive Summary</div>
        """, unsafe_allow_html=True)
        
        if insights and "summary" in insights and insights["summary"]:
            st.markdown(f"""
                <div class="reborn-content">{insights["summary"]}</div>
            """, unsafe_allow_html=True)
        else:
            st.info("No detailed executive summary is available.")

        # Display performance insights
        st.markdown("""
            <div class="reborn-section-title insights">Key Performance Insights</div>
        """, unsafe_allow_html=True)
        
        if insights and "performance" in insights and insights["performance"]:
            insights_html = ""
            for point in insights["performance"]:
                insights_html += f"<p>• {point}</p>"
            
            st.markdown(f"""
                <div class="reborn-content">{insights_html}</div>
            """, unsafe_allow_html=True)
        else:
            st.info("No detailed performance insights are available.")

        # Display recommendations
        st.markdown("""
            <div class="reborn-section-title recommendations">Recommendations</div>
        """, unsafe_allow_html=True)
        
        if insights and "recommendations" in insights and insights["recommendations"]:
            recommendations_html = ""
            for rec in insights["recommendations"]:
                recommendations_html += f"<p>• {rec}</p>"
            
            st.markdown(f"""
                <div class="reborn-content">{recommendations_html}</div>
            """, unsafe_allow_html=True)
        else:
            st.info("No detailed recommendations are available.")

        # Add a divider
        st.markdown("---")

        # Add a note about AI generation
        st.caption("These insights were generated by AI based on the detailed financial data provided.")
