services:
  - type: web
    name: noi-analyzer-api
    env: python
    buildCommand: echo "Build complete - no dependencies needed"
    startCommand: python simple_server.py
    plan: free
    envVars:
      - key: PORT
        value: 10000 