services:
  # Main NOI Analyzer Application
  - type: web
    name: noianalyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT
    plan: free
    envVars:
      - key: PORT
        value: 8501
      - key: BACKEND_URL
        value: https://noianalyzer-1.onrender.com
      - key: OPENAI_API_KEY
        sync: false
      - key: EXTRACTION_API_KEY
        sync: false
      - key: EXTRACTION_API_URL
        value: https://dataextractionai.onrender.com

  # Credit Service
  - type: web
    name: noianalyzer-1
    env: python
    # Specify Python version to ensure compatibility
    buildCommand: pip install -r requirements-api.txt
    startCommand: python start_credit_api.py
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_STARTER_PRICE_ID
        sync: false
      - key: STRIPE_PROFESSIONAL_PRICE_ID
        sync: false
      - key: STRIPE_BUSINESS_PRICE_ID
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: CREDIT_SUCCESS_URL
        value: https://noianalyzer.onrender.com/credit-success?session_id={CHECKOUT_SESSION_ID}&email={email}
      - key: CREDIT_CANCEL_URL
        value: https://noianalyzer.onrender.com/payment-cancel
      - key: BACKEND_URL
        value: https://noianalyzer-1.onrender.com