services:
  - type: web
    name: noi-analyzer-api
    env: python
    buildCommand: pip install -r requirements-api.txt
    startCommand: uvicorn api_server_credit_only:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    # Add your environment variables here:
    # - key: STRIPE_SECRET_KEY
    #   value: your_stripe_secret_key
    # - key: RESEND_API_KEY  
    #   value: your_resend_api_key 