services:
  - type: web
    name: noi-analyzer-api
    env: python
    buildCommand: echo "No dependencies needed - using pure Python!"
    startCommand: python ultra_minimal_api.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
    # Add your environment variables here:
    # - key: STRIPE_SECRET_KEY
    #   value: your_stripe_secret_key
    # - key: RESEND_API_KEY  
    #   value: your_resend_api_key 