services:
  # Main NOI Analyzer Application
  - type: web
    name: noianalyzer
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    plan: free
    envVars:
      - key: PORT
        value: 8501
      - key: BACKEND_URL
        value: https://noianalyzer-1.onrender.com
      - key: OPENAI_API_KEY
        sync: false
      - key: EXTRACTION_API_KEY
        sync: false
      - key: EXTRACTION_API_URL
        value: https://dataextractionai.onrender.com
      - key: DISABLE_POETRY
        value: 1
      - key: UV_INSTALL_PURELIB
        value: 0

  # Credit Service (Stripe Payment API)
  # This service handles all credit and payment processing
  # It requires the stripe library to be installed via requirements-api.txt
  - type: web
    name: noianalyzer-1
    env: python
    # Build command installs all required dependencies including stripe
    buildCommand: pip install --no-cache-dir -r requirements-api.txt
    # Start command runs the credit API server
    startCommand: python start_credit_api.py
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_STARTER_PRICE_ID
        sync: false
      - key: STRIPE_PROFESSIONAL_PRICE_ID
        sync: false
      - key: STRIPE_BUSINESS_PRICE_ID
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: CREDIT_SUCCESS_URL
        value: https://noianalyzer.onrender.com/credit-success?session_id={CHECKOUT_SESSION_ID}&email={email}
      - key: CREDIT_CANCEL_URL
        value: https://noianalyzer.onrender.com/payment-cancel
      - key: BACKEND_URL
        value: https://noianalyzer-1.onrender.com
      - key: DISABLE_POETRY
        value: 1
      - key: UV_INSTALL_PURELIB
        value: 0