[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
baseUrlPath = ""

[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false
